### ISSUE TITLE
Command "deploy" is not defined.

### ISSUE THREAD

**Issue by CawaKharkov** [deployphp/docs#12]
Command "deploy" is not defined.

**Comment by elfet** [comment]
Plz, show your `deploy.php` file.

**Comment by CawaKharkov** [comment]
It's just a copy of deploy.php from examples:

```php
<?php

require 'recipe/common.php';


// Define server for deploy.
// Let's name it "main" and use 22 port.
server('main', '...', 22)
    ->path('/home/www/project') 
    ->user('name', 'password'); 

set('repository', 'git@github');
```

**Comment by maykino** [comment]
Same problem here. What is the solution?

**Comment by oanhnn** [comment]
@maykino Please show more info (OS, shell type, `deploy.php`)

**Comment by Sartor** [comment]
I have same problem. Fresh install. Config file:
`<?php

require 'recipe/common.php';

server('prod', 'sartorua.com', 22)
    ->user('sartor')
    //->forwardAgent() // You can use identity key, ssh config, or username/password to auth on the server.
    ->stage('production')
    ->env('deploy_path', 'laravel'); // Define the base path to deploy your project to.

set('repository', 'sartor@sartorua.com:git/laravel.git');

// Laravel shared dirs
set('shared_dirs', [
    'storage/app',
    'storage/framework/cache',
    'storage/framework/sessions',
    'storage/framework/views',
    'storage/logs',
]);

// Laravel 5 shared file
set('shared_files', ['.env']);

// Laravel writable dirs
set('writable_dirs', ['storage', 'vendor']);`

In projects root: dep deploy production
Output: 
`[Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "deploy" is not defined.                                
  Did you mean one of these?                                      
      deploy:update_code                                          
      deploy:copy_dirs                                            
      deploy:writable                                             
      deploy:vendors                                              
      deploy:release                                              
      deploy:prepare                                              
      deploy:symlink                                              
      deploy:shared        `

**Comment by elfet** [comment]
Common recipe does not contain deploy command. The process of deploy you must configure your self.
May be add default list to common recipe?
