### ISSUE TITLE
Migration documentation for v3.0.0

### ISSUE THREAD

**Issue by tomzx** [deployphp/docs#4]
Hi,

I've created a [gist](https://gist.githubusercontent.com/tomzx/06b572a65d7053b94f71/raw/a86e13d2b0032ccc5a86d1ff96499a994eae0161/semver-changes-v3.0.0-beta2) using [php-semver-checker](https://github.com/tomzx/php-semver-checker) which should help figuring out what will need to be part of the migration documentation.

I think what will be the most notable changes are the functions users are used to use to declare their deployments.

Let me know if you have any questions.

**Comment by elfet** [comment]
Yes, hard work on docs for v3 will begin. :beginner:

**Comment by tomzx** [comment]
FYI, I've started improving the current documentation in preparation for v3. It is mostly English fixes, but I think it'll pave the way for the v3 documentation.

**Comment by elfet** [comment]
So cool! :+1:

**Comment by erickr** [comment]
Is there a branch available with the docs changes? The website and the docs are very misleading, leading people to download v3 and then reading docs with examples which doesnt work with the downloaded version.

**Comment by elfet** [comment]
Now master branch is for v3.
