### ISSUE TITLE
[Add] Add composer autoload tip against namespace issues

### ISSUE THREAD

**Issue by JHGitty** [deployphp/docs#44]
I think we should add the following tip to the documentation for Deployer version 3.
This is a workaround for issues https://github.com/deployphp/deployer/issues/316, https://github.com/deployphp/deployer/issues/356, ..

**Edit: This workaround only works for classes and not for functions.**

You must use composer to use this workaround.

Add this to your own ``composer.json`` file:
```json
  "autoload": {
    "psr-4": {
      "Deployer\\": "vendor/deployer/deployer/"
    }
  },
```

Then you can use Deployer with namespace:
```php
require __DIR__ . '/vendor/autoload.php';

use Deployer;

// ...
```

**Comment by elfet** [comment]
:+1:

**Comment by JHGitty** [comment]
Oh, I am wrong. We cannot use it like this because it only works for classes and not for functions. I am looking forward to get any workaround for it ..

**Comment by elfet** [comment]
```
use function Deployer;
```

**Comment by JHGitty** [comment]
Okay, thanks. Is this tip anywhere in the current documentation? If not we should add it for version 3.
There should be a notice that it is only available for PHP5.6+.

**Comment by elfet** [comment]
Can you make PR?

**Comment by JHGitty** [comment]
No time for it, just to report it here. I hope somebody else can do a Pull Request for it.

**Comment by elfet** [comment]
I think we all haven’t time :)

**Comment by JHGitty** [comment]
There should be a new issue "Add ... to documentation".

**Comment by nakashu** [comment]
Can anyone post a bit more complete code for this workaround?

I understand the composer part with autolading, but where would you use the `use function Deployer` in your recipe ? 
Because that way it doesn't work, I still get the cannot redeclare set(), from hamcrest.

**Comment by elfet** [comment]
Or `namespace Deployer;`

**Comment by pluseg** [comment]
@elfet 
What's status of the issue? I read that you want to fix it in next major (4) version. When is it planned to release?
May be you need some help? I can code it.

**Comment by elfet** [comment]
Take a look at 4.x branch. There is a namespaces already. I'm planing to release it as soon as possible, but i do not know then, i need to work)

**Comment by williamn** [comment]
@nakashu Did you manage to resolve the issue? I use 4.x-dev version and added `namespace Deployer;` in my deploy.php to make it works

**Comment by nakashu** [comment]
@williamn no I didn't .. 
As I use 3.x version on that project, when i added `namespace Deployer;` it didn't work as the code couldn't be found by the script then.
Did a dirty workaround as it was a small project.. I deleted the conflicting method from the other library in my local vendor directory from where I was running the deployment.

**Comment by rdohms** [comment]
Can someone post something that actually describes the full work around?
Having a hard time trying to piece together loose answers like "or this" and "or that"  :(
