### ISSUE TITLE
How to see all the tasks for a given deploy?

### ISSUE THREAD

**Issue by achristodoulou** [deployphp/docs#53]
Hi,

Is there any command that will list all the tasks for a given deploy?

Example:

```
dep deploy production --dry-run

✔ Task deploy:prepare
✔ Task deploy:release
✔ Task deploy:update_code
✔ Task deploy:clear_controllers
✔ Task deploy:create_cache_dir
✔ Task deploy:shared
✔ Task deploy:writable
✔ Task deploy:assets
✔ Task deploy:copy_dirs
✔ Task deploy:vendors
✔ Task deploy:assetic:dump
✔ Task deploy:cache:warmup
✔ Task deploy:symlink
✔ Task cleanup
✔ Task success

```

**Comment by pluseg** [comment]
@achristodoulou Andreas, there is `dep list` which displays all available tasks. 

There is no command for task listing of concrete deploy. First of all, it's too complicated to figure out such tasks as there are `after()`, `before()` hooks and conditional steps depending on environment configuration. Second and the main, it's not necessary at all. You have such task lists in your `deploy.php` file and in a concrete recipe (f.e. `symfony.php`) by searching `deploy` task.

**Comment by elfet** [comment]
I think `dep help deploy` can help (note, this is not implemented yet)
