### ISSUE TITLE
Current version have a syntax error

### ISSUE THREAD

**Issue by acacha** [deployphp/docs#6]
$ wget http://deployer.org/deployer.phar
$ sudo mv deployer.phar /usr/bin/dep
$ sudo chmod +x /usr/bin/dep
$ dep self-update
o
$ dep
PHP Parse error:  syntax error, unexpected '[' in phar:///usr/bin/dep/src/Deployer.php on line 52

**Comment by elfet** [comment]
Yeah... Sorry about that is't php 5.4 (buy the way, it's new requirement for Deployer 3). Will fix it.

**Comment by elfet** [comment]
Done.
