### ISSUE TITLE
Usage of deployer with composer

### ISSUE THREAD

**Issue by Silverdark** [deployphp/docs#69]
If I install the deployer with the command `composer require deployer/deployer` it creates two file in the vendor/bin folder, a 'dep' and a 'dep.bat' file.

Both of them aren't PHP files, but the instruction says you should run following command: `php vendor/bin/dep` which leads to the result:

```
dir=$(d=${0%[/\\]*}; cd "$d"; cd "../deployer/deployer/bin" && pwd)

# See if we are running in Cygwin by checking for cygpath program
if command -v 'cygpath' >/dev/null 2>&1; then
        # Cygwin paths start with /cygdrive/ which will break windows PHP,
        # so we need to translate the dir path to windows format. However
        # we could be using cygwin PHP which does not require this, so we
        # test if the path to PHP starts with /cygdrive/ rather than /usr/bin
        if [[ $(which php) == /cygdrive/* ]]; then
                dir=$(cygpath -m "$dir");
        fi
fi

dir=$(echo $dir | sed 's/ /\ /g')
"${dir}/dep" "$@"
```

If I use the command `call vendor/bin/dep` it works, with the result:

```
Deployer master

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -f, --file[=FILE]     Specify Deployer file
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  help    Displays help for a command
  init    Initialize deployer system in your project
  list    Lists commands
  worker  Deployer uses workers for parallel deployment
```

I don't think this is related to my operating system (Windows 10) and because of that, the instructions for the composer usage should be revised.

**Comment by elfet** [comment]
Cygwin. `php vendor/bin/dep` correct.

**Comment by Silverdark** [comment]
![cmd_2017-01-01_15-40-17](https://cloud.githubusercontent.com/assets/3630571/21581609/e75ff900-d038-11e6-9547-582367f9969a.png)
Censored only user name, computer name and actual project.

The php command doesn't work, but the direct call with `./vendor/bin/dep` works.

**Comment by elfet** [comment]
I think it's your environmental issues.

**Comment by pluseg** [comment]
@Silverdark Daniel, did you figure out the cause root?
