### ISSUE TITLE
documentation about secrets/credentials

### ISSUE THREAD

**Issue by glensc** [deployphp/docs#73]
https://deployer.org/docs/servers

writes examples how to store passwords in deployer.php
however, it's not good practice to keep passwords in vcs
so they should likely be stored in env variables

need examples and best pratices for that.

also: the secrets could be in some other place too
like slack token: https://github.com/deployphp/recipes/blob/4.0.4/slack.php#L39
https://deployer.org/recipes/slack

**Comment by glensc** [comment]
do you have example how to use os env variables? and fallback to get()?

**Comment by elfet** [comment]
getenv()

**Comment by pluseg** [comment]
@elfet I guess you can close this issue.
