### ISSUE TITLE
Broken link to hosts.md

### ISSUE THREAD

**Issue by shakyj** [deployphp/docs#90]
https://deployer.org/docs/getting-started links 
has a 404 link titled "inventory" to 
https://deployer.org/docs/hosts.md#inventory-file
The whole hosts.md file 404s
The files look right and link right in github so maybe it just needs a redeploy

**Comment by shakyj** [comment]
Looks like it should link to here 
https://deployer.org/docs/hosts#inventory-file
If we change it in the source it will no longer work on github
Maybe you could use mod rewrite to rewrite all .md urls the url without .md?

**Comment by antonmedv** [comment]
I'll fix it here: https://github.com/deployphp/deployer.org/blob/master/src/helpers.php#L81
