### ISSUE TITLE
Task pwd from docs, unexpected behavior, deploy_path is ignored

### ISSUE THREAD

**Issue by EnricoSottile** [deployphp/docs#92]
In following the  [getting started](https://github.com/deployphp/docs/blob/master/getting-started.md) section of the docs, the **deploy_path** specified in the server section is ignored when i run the task.

Running `dep pwd`, should output:
```
➤ Executing task pwd
Current dir: /path/to/folder
✔ Ok
```

But instead i get the user's home folder:
```
➤ Executing task pwd
Current dir: /home/myuser
✔ Ok
```

This is my server config:
```
server('production', 'myserver')
    ->user('myuser')
    ->set('deploy_path', '/path/to/folder')
    ->pty(true);
```

**Comment by antonmedv** [comment]
Works for me. Please provide example.

**Comment by EnricoSottile** [comment]
Hello and thanks for your quick answer.
I am running the code from my local machine to an aws server, and I don't know how to provide the example.

I forgot to mention that I'm using v4.3.0.

I've tried to do this, but the output remains the user's home folder:
```
task('pwd', function () {
    run('cd /var/www');
    $result = run('pwd');
    writeln("Current dir: $result");
})->desc('Test function');
```

**Comment by antonmedv** [comment]
Remove  this line `run('cd /var/www');`

**Comment by EnricoSottile** [comment]
That was just me trying something different. The presence of that line does not change the final result of running `dep pwd`

**Comment by antonmedv** [comment]
Fixed.

**Comment by EnricoSottile** [comment]
In the Issue I mentioned seems clear that running a command from the user's home directory is the common behavior, but in the docs this is not specified.
Am I missing something?

**Comment by antonmedv** [comment]
I think we need better docs here, by default `~` is preferred. Only in https://deployer.org/docs/tasks#simple-tasks used `release_path`

**Comment by EnricoSottile** [comment]
So basically the code is correct but the docs are wrong.
I will try to get the time to modify them if that's ok.
